// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dict is the predicate function for dict builders.
type Dict func(*sql.Selector)

// DictType is the predicate function for dicttype builders.
type DictType func(*sql.Selector)
