// Code generated by entc, DO NOT EDIT.

package accountuser

const (
	// Label holds the string label denoting the accountuser type in the database.
	Label = "account_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldCreateIPAt holds the string denoting the create_ip_at field in the database.
	FieldCreateIPAt = "create_ip_at"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldLastLoginIPAt holds the string denoting the last_login_ip_at field in the database.
	FieldLastLoginIPAt = "last_login_ip_at"
	// FieldLoginTimes holds the string denoting the login_times field in the database.
	FieldLoginTimes = "login_times"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the accountuser in the database.
	Table = "account_users"
)

// Columns holds all SQL columns for accountuser fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPhone,
	FieldUsername,
	FieldPassword,
	FieldCreateAt,
	FieldCreateIPAt,
	FieldLastLoginAt,
	FieldLastLoginIPAt,
	FieldLoginTimes,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// DefaultPhone holds the default value on creation for the "phone" field.
	DefaultPhone string
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultPassword holds the default value on creation for the "password" field.
	DefaultPassword string
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt int32
	// DefaultCreateIPAt holds the default value on creation for the "create_ip_at" field.
	DefaultCreateIPAt string
	// DefaultLastLoginAt holds the default value on creation for the "last_login_at" field.
	DefaultLastLoginAt int32
	// DefaultLastLoginIPAt holds the default value on creation for the "last_login_ip_at" field.
	DefaultLastLoginIPAt string
	// DefaultLoginTimes holds the default value on creation for the "login_times" field.
	DefaultLoginTimes int32
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
)
