// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lalifeier/vgo/app/ums/service/internal/data/ent/accountplatform"
	"github.com/lalifeier/vgo/app/ums/service/internal/data/ent/predicate"
)

// AccountPlatformUpdate is the builder for updating AccountPlatform entities.
type AccountPlatformUpdate struct {
	config
	hooks    []Hook
	mutation *AccountPlatformMutation
}

// Where appends a list predicates to the AccountPlatformUpdate builder.
func (apu *AccountPlatformUpdate) Where(ps ...predicate.AccountPlatform) *AccountPlatformUpdate {
	apu.mutation.Where(ps...)
	return apu
}

// SetUID sets the "uid" field.
func (apu *AccountPlatformUpdate) SetUID(i int32) *AccountPlatformUpdate {
	apu.mutation.ResetUID()
	apu.mutation.SetUID(i)
	return apu
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillableUID(i *int32) *AccountPlatformUpdate {
	if i != nil {
		apu.SetUID(*i)
	}
	return apu
}

// AddUID adds i to the "uid" field.
func (apu *AccountPlatformUpdate) AddUID(i int32) *AccountPlatformUpdate {
	apu.mutation.AddUID(i)
	return apu
}

// SetPlatformID sets the "platform_id" field.
func (apu *AccountPlatformUpdate) SetPlatformID(s string) *AccountPlatformUpdate {
	apu.mutation.SetPlatformID(s)
	return apu
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillablePlatformID(s *string) *AccountPlatformUpdate {
	if s != nil {
		apu.SetPlatformID(*s)
	}
	return apu
}

// SetPlatformToken sets the "platform_token" field.
func (apu *AccountPlatformUpdate) SetPlatformToken(s string) *AccountPlatformUpdate {
	apu.mutation.SetPlatformToken(s)
	return apu
}

// SetNillablePlatformToken sets the "platform_token" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillablePlatformToken(s *string) *AccountPlatformUpdate {
	if s != nil {
		apu.SetPlatformToken(*s)
	}
	return apu
}

// SetType sets the "type" field.
func (apu *AccountPlatformUpdate) SetType(i int8) *AccountPlatformUpdate {
	apu.mutation.ResetType()
	apu.mutation.SetType(i)
	return apu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillableType(i *int8) *AccountPlatformUpdate {
	if i != nil {
		apu.SetType(*i)
	}
	return apu
}

// AddType adds i to the "type" field.
func (apu *AccountPlatformUpdate) AddType(i int8) *AccountPlatformUpdate {
	apu.mutation.AddType(i)
	return apu
}

// SetNickname sets the "nickname" field.
func (apu *AccountPlatformUpdate) SetNickname(s string) *AccountPlatformUpdate {
	apu.mutation.SetNickname(s)
	return apu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillableNickname(s *string) *AccountPlatformUpdate {
	if s != nil {
		apu.SetNickname(*s)
	}
	return apu
}

// SetAvatar sets the "avatar" field.
func (apu *AccountPlatformUpdate) SetAvatar(s string) *AccountPlatformUpdate {
	apu.mutation.SetAvatar(s)
	return apu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillableAvatar(s *string) *AccountPlatformUpdate {
	if s != nil {
		apu.SetAvatar(*s)
	}
	return apu
}

// SetCreateAt sets the "create_at" field.
func (apu *AccountPlatformUpdate) SetCreateAt(i int32) *AccountPlatformUpdate {
	apu.mutation.ResetCreateAt()
	apu.mutation.SetCreateAt(i)
	return apu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillableCreateAt(i *int32) *AccountPlatformUpdate {
	if i != nil {
		apu.SetCreateAt(*i)
	}
	return apu
}

// AddCreateAt adds i to the "create_at" field.
func (apu *AccountPlatformUpdate) AddCreateAt(i int32) *AccountPlatformUpdate {
	apu.mutation.AddCreateAt(i)
	return apu
}

// SetUpdateAt sets the "update_at" field.
func (apu *AccountPlatformUpdate) SetUpdateAt(i int32) *AccountPlatformUpdate {
	apu.mutation.ResetUpdateAt()
	apu.mutation.SetUpdateAt(i)
	return apu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (apu *AccountPlatformUpdate) SetNillableUpdateAt(i *int32) *AccountPlatformUpdate {
	if i != nil {
		apu.SetUpdateAt(*i)
	}
	return apu
}

// AddUpdateAt adds i to the "update_at" field.
func (apu *AccountPlatformUpdate) AddUpdateAt(i int32) *AccountPlatformUpdate {
	apu.mutation.AddUpdateAt(i)
	return apu
}

// Mutation returns the AccountPlatformMutation object of the builder.
func (apu *AccountPlatformUpdate) Mutation() *AccountPlatformMutation {
	return apu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (apu *AccountPlatformUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(apu.hooks) == 0 {
		affected, err = apu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountPlatformMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			apu.mutation = mutation
			affected, err = apu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(apu.hooks) - 1; i >= 0; i-- {
			if apu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = apu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, apu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (apu *AccountPlatformUpdate) SaveX(ctx context.Context) int {
	affected, err := apu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (apu *AccountPlatformUpdate) Exec(ctx context.Context) error {
	_, err := apu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apu *AccountPlatformUpdate) ExecX(ctx context.Context) {
	if err := apu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (apu *AccountPlatformUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountplatform.Table,
			Columns: accountplatform.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: accountplatform.FieldID,
			},
		},
	}
	if ps := apu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apu.mutation.UID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUID,
		})
	}
	if value, ok := apu.mutation.AddedUID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUID,
		})
	}
	if value, ok := apu.mutation.PlatformID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldPlatformID,
		})
	}
	if value, ok := apu.mutation.PlatformToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldPlatformToken,
		})
	}
	if value, ok := apu.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: accountplatform.FieldType,
		})
	}
	if value, ok := apu.mutation.AddedType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: accountplatform.FieldType,
		})
	}
	if value, ok := apu.mutation.Nickname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldNickname,
		})
	}
	if value, ok := apu.mutation.Avatar(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldAvatar,
		})
	}
	if value, ok := apu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldCreateAt,
		})
	}
	if value, ok := apu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldCreateAt,
		})
	}
	if value, ok := apu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUpdateAt,
		})
	}
	if value, ok := apu.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUpdateAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, apu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountplatform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AccountPlatformUpdateOne is the builder for updating a single AccountPlatform entity.
type AccountPlatformUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountPlatformMutation
}

// SetUID sets the "uid" field.
func (apuo *AccountPlatformUpdateOne) SetUID(i int32) *AccountPlatformUpdateOne {
	apuo.mutation.ResetUID()
	apuo.mutation.SetUID(i)
	return apuo
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillableUID(i *int32) *AccountPlatformUpdateOne {
	if i != nil {
		apuo.SetUID(*i)
	}
	return apuo
}

// AddUID adds i to the "uid" field.
func (apuo *AccountPlatformUpdateOne) AddUID(i int32) *AccountPlatformUpdateOne {
	apuo.mutation.AddUID(i)
	return apuo
}

// SetPlatformID sets the "platform_id" field.
func (apuo *AccountPlatformUpdateOne) SetPlatformID(s string) *AccountPlatformUpdateOne {
	apuo.mutation.SetPlatformID(s)
	return apuo
}

// SetNillablePlatformID sets the "platform_id" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillablePlatformID(s *string) *AccountPlatformUpdateOne {
	if s != nil {
		apuo.SetPlatformID(*s)
	}
	return apuo
}

// SetPlatformToken sets the "platform_token" field.
func (apuo *AccountPlatformUpdateOne) SetPlatformToken(s string) *AccountPlatformUpdateOne {
	apuo.mutation.SetPlatformToken(s)
	return apuo
}

// SetNillablePlatformToken sets the "platform_token" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillablePlatformToken(s *string) *AccountPlatformUpdateOne {
	if s != nil {
		apuo.SetPlatformToken(*s)
	}
	return apuo
}

// SetType sets the "type" field.
func (apuo *AccountPlatformUpdateOne) SetType(i int8) *AccountPlatformUpdateOne {
	apuo.mutation.ResetType()
	apuo.mutation.SetType(i)
	return apuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillableType(i *int8) *AccountPlatformUpdateOne {
	if i != nil {
		apuo.SetType(*i)
	}
	return apuo
}

// AddType adds i to the "type" field.
func (apuo *AccountPlatformUpdateOne) AddType(i int8) *AccountPlatformUpdateOne {
	apuo.mutation.AddType(i)
	return apuo
}

// SetNickname sets the "nickname" field.
func (apuo *AccountPlatformUpdateOne) SetNickname(s string) *AccountPlatformUpdateOne {
	apuo.mutation.SetNickname(s)
	return apuo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillableNickname(s *string) *AccountPlatformUpdateOne {
	if s != nil {
		apuo.SetNickname(*s)
	}
	return apuo
}

// SetAvatar sets the "avatar" field.
func (apuo *AccountPlatformUpdateOne) SetAvatar(s string) *AccountPlatformUpdateOne {
	apuo.mutation.SetAvatar(s)
	return apuo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillableAvatar(s *string) *AccountPlatformUpdateOne {
	if s != nil {
		apuo.SetAvatar(*s)
	}
	return apuo
}

// SetCreateAt sets the "create_at" field.
func (apuo *AccountPlatformUpdateOne) SetCreateAt(i int32) *AccountPlatformUpdateOne {
	apuo.mutation.ResetCreateAt()
	apuo.mutation.SetCreateAt(i)
	return apuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillableCreateAt(i *int32) *AccountPlatformUpdateOne {
	if i != nil {
		apuo.SetCreateAt(*i)
	}
	return apuo
}

// AddCreateAt adds i to the "create_at" field.
func (apuo *AccountPlatformUpdateOne) AddCreateAt(i int32) *AccountPlatformUpdateOne {
	apuo.mutation.AddCreateAt(i)
	return apuo
}

// SetUpdateAt sets the "update_at" field.
func (apuo *AccountPlatformUpdateOne) SetUpdateAt(i int32) *AccountPlatformUpdateOne {
	apuo.mutation.ResetUpdateAt()
	apuo.mutation.SetUpdateAt(i)
	return apuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (apuo *AccountPlatformUpdateOne) SetNillableUpdateAt(i *int32) *AccountPlatformUpdateOne {
	if i != nil {
		apuo.SetUpdateAt(*i)
	}
	return apuo
}

// AddUpdateAt adds i to the "update_at" field.
func (apuo *AccountPlatformUpdateOne) AddUpdateAt(i int32) *AccountPlatformUpdateOne {
	apuo.mutation.AddUpdateAt(i)
	return apuo
}

// Mutation returns the AccountPlatformMutation object of the builder.
func (apuo *AccountPlatformUpdateOne) Mutation() *AccountPlatformMutation {
	return apuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (apuo *AccountPlatformUpdateOne) Select(field string, fields ...string) *AccountPlatformUpdateOne {
	apuo.fields = append([]string{field}, fields...)
	return apuo
}

// Save executes the query and returns the updated AccountPlatform entity.
func (apuo *AccountPlatformUpdateOne) Save(ctx context.Context) (*AccountPlatform, error) {
	var (
		err  error
		node *AccountPlatform
	)
	if len(apuo.hooks) == 0 {
		node, err = apuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountPlatformMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			apuo.mutation = mutation
			node, err = apuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(apuo.hooks) - 1; i >= 0; i-- {
			if apuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = apuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, apuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (apuo *AccountPlatformUpdateOne) SaveX(ctx context.Context) *AccountPlatform {
	node, err := apuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (apuo *AccountPlatformUpdateOne) Exec(ctx context.Context) error {
	_, err := apuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apuo *AccountPlatformUpdateOne) ExecX(ctx context.Context) {
	if err := apuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (apuo *AccountPlatformUpdateOne) sqlSave(ctx context.Context) (_node *AccountPlatform, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   accountplatform.Table,
			Columns: accountplatform.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: accountplatform.FieldID,
			},
		},
	}
	id, ok := apuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing AccountPlatform.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := apuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountplatform.FieldID)
		for _, f := range fields {
			if !accountplatform.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountplatform.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := apuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apuo.mutation.UID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUID,
		})
	}
	if value, ok := apuo.mutation.AddedUID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUID,
		})
	}
	if value, ok := apuo.mutation.PlatformID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldPlatformID,
		})
	}
	if value, ok := apuo.mutation.PlatformToken(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldPlatformToken,
		})
	}
	if value, ok := apuo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: accountplatform.FieldType,
		})
	}
	if value, ok := apuo.mutation.AddedType(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: accountplatform.FieldType,
		})
	}
	if value, ok := apuo.mutation.Nickname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldNickname,
		})
	}
	if value, ok := apuo.mutation.Avatar(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: accountplatform.FieldAvatar,
		})
	}
	if value, ok := apuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldCreateAt,
		})
	}
	if value, ok := apuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldCreateAt,
		})
	}
	if value, ok := apuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUpdateAt,
		})
	}
	if value, ok := apuo.mutation.AddedUpdateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: accountplatform.FieldUpdateAt,
		})
	}
	_node = &AccountPlatform{config: apuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, apuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountplatform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
