// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/lalifeier/vgo/app/ums/service/internal/data/ent/accountplatform"
	"github.com/lalifeier/vgo/app/ums/service/internal/data/ent/accountuser"
	"github.com/lalifeier/vgo/app/ums/service/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountplatformFields := schema.AccountPlatform{}.Fields()
	_ = accountplatformFields
	// accountplatformDescUID is the schema descriptor for uid field.
	accountplatformDescUID := accountplatformFields[1].Descriptor()
	// accountplatform.DefaultUID holds the default value on creation for the uid field.
	accountplatform.DefaultUID = accountplatformDescUID.Default.(int32)
	// accountplatformDescPlatformID is the schema descriptor for platform_id field.
	accountplatformDescPlatformID := accountplatformFields[2].Descriptor()
	// accountplatform.DefaultPlatformID holds the default value on creation for the platform_id field.
	accountplatform.DefaultPlatformID = accountplatformDescPlatformID.Default.(string)
	// accountplatformDescPlatformToken is the schema descriptor for platform_token field.
	accountplatformDescPlatformToken := accountplatformFields[3].Descriptor()
	// accountplatform.DefaultPlatformToken holds the default value on creation for the platform_token field.
	accountplatform.DefaultPlatformToken = accountplatformDescPlatformToken.Default.(string)
	// accountplatformDescType is the schema descriptor for type field.
	accountplatformDescType := accountplatformFields[4].Descriptor()
	// accountplatform.DefaultType holds the default value on creation for the type field.
	accountplatform.DefaultType = accountplatformDescType.Default.(int8)
	// accountplatformDescNickname is the schema descriptor for nickname field.
	accountplatformDescNickname := accountplatformFields[5].Descriptor()
	// accountplatform.DefaultNickname holds the default value on creation for the nickname field.
	accountplatform.DefaultNickname = accountplatformDescNickname.Default.(string)
	// accountplatformDescAvatar is the schema descriptor for avatar field.
	accountplatformDescAvatar := accountplatformFields[6].Descriptor()
	// accountplatform.DefaultAvatar holds the default value on creation for the avatar field.
	accountplatform.DefaultAvatar = accountplatformDescAvatar.Default.(string)
	// accountplatformDescCreateAt is the schema descriptor for create_at field.
	accountplatformDescCreateAt := accountplatformFields[7].Descriptor()
	// accountplatform.DefaultCreateAt holds the default value on creation for the create_at field.
	accountplatform.DefaultCreateAt = accountplatformDescCreateAt.Default.(int32)
	// accountplatformDescUpdateAt is the schema descriptor for update_at field.
	accountplatformDescUpdateAt := accountplatformFields[8].Descriptor()
	// accountplatform.DefaultUpdateAt holds the default value on creation for the update_at field.
	accountplatform.DefaultUpdateAt = accountplatformDescUpdateAt.Default.(int32)
	accountuserFields := schema.AccountUser{}.Fields()
	_ = accountuserFields
	// accountuserDescEmail is the schema descriptor for email field.
	accountuserDescEmail := accountuserFields[1].Descriptor()
	// accountuser.DefaultEmail holds the default value on creation for the email field.
	accountuser.DefaultEmail = accountuserDescEmail.Default.(string)
	// accountuserDescPhone is the schema descriptor for phone field.
	accountuserDescPhone := accountuserFields[2].Descriptor()
	// accountuser.DefaultPhone holds the default value on creation for the phone field.
	accountuser.DefaultPhone = accountuserDescPhone.Default.(string)
	// accountuserDescUsername is the schema descriptor for username field.
	accountuserDescUsername := accountuserFields[3].Descriptor()
	// accountuser.DefaultUsername holds the default value on creation for the username field.
	accountuser.DefaultUsername = accountuserDescUsername.Default.(string)
	// accountuserDescPassword is the schema descriptor for password field.
	accountuserDescPassword := accountuserFields[4].Descriptor()
	// accountuser.DefaultPassword holds the default value on creation for the password field.
	accountuser.DefaultPassword = accountuserDescPassword.Default.(string)
	// accountuserDescCreateAt is the schema descriptor for create_at field.
	accountuserDescCreateAt := accountuserFields[5].Descriptor()
	// accountuser.DefaultCreateAt holds the default value on creation for the create_at field.
	accountuser.DefaultCreateAt = accountuserDescCreateAt.Default.(int32)
	// accountuserDescCreateIPAt is the schema descriptor for create_ip_at field.
	accountuserDescCreateIPAt := accountuserFields[6].Descriptor()
	// accountuser.DefaultCreateIPAt holds the default value on creation for the create_ip_at field.
	accountuser.DefaultCreateIPAt = accountuserDescCreateIPAt.Default.(string)
	// accountuserDescLastLoginAt is the schema descriptor for last_login_at field.
	accountuserDescLastLoginAt := accountuserFields[7].Descriptor()
	// accountuser.DefaultLastLoginAt holds the default value on creation for the last_login_at field.
	accountuser.DefaultLastLoginAt = accountuserDescLastLoginAt.Default.(int32)
	// accountuserDescLastLoginIPAt is the schema descriptor for last_login_ip_at field.
	accountuserDescLastLoginIPAt := accountuserFields[8].Descriptor()
	// accountuser.DefaultLastLoginIPAt holds the default value on creation for the last_login_ip_at field.
	accountuser.DefaultLastLoginIPAt = accountuserDescLastLoginIPAt.Default.(string)
	// accountuserDescLoginTimes is the schema descriptor for login_times field.
	accountuserDescLoginTimes := accountuserFields[9].Descriptor()
	// accountuser.DefaultLoginTimes holds the default value on creation for the login_times field.
	accountuser.DefaultLoginTimes = accountuserDescLoginTimes.Default.(int32)
	// accountuserDescStatus is the schema descriptor for status field.
	accountuserDescStatus := accountuserFields[10].Descriptor()
	// accountuser.DefaultStatus holds the default value on creation for the status field.
	accountuser.DefaultStatus = accountuserDescStatus.Default.(int8)
}
