// Code generated by entc, DO NOT EDIT.

package api

import (
	"time"

	"entgo.io/ent"
)

const (
	// Label holds the string label denoting the api type in the database.
	Label = "api"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldGroup holds the string denoting the group field in the database.
	FieldGroup = "group"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldPermission holds the string denoting the permission field in the database.
	FieldPermission = "permission"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the api in the database.
	Table = "sys_api"
)

// Columns holds all SQL columns for api fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCreatedBy,
	FieldUpdatedAt,
	FieldUpdatedBy,
	FieldGroup,
	FieldName,
	FieldPath,
	FieldMethod,
	FieldDesc,
	FieldPermission,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/lalifeier/vvgo-mall/app/shop/admin/internal/data/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultUpdatedBy holds the default value on creation for the "updated_by" field.
	DefaultUpdatedBy int64
	// DefaultGroup holds the default value on creation for the "group" field.
	DefaultGroup string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultPath holds the default value on creation for the "path" field.
	DefaultPath string
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// DefaultDesc holds the default value on creation for the "desc" field.
	DefaultDesc string
	// DefaultPermission holds the default value on creation for the "permission" field.
	DefaultPermission string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
)
