// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/lalifeier/vvgo-mall/app/sys/service/internal/data/ent/dict"
	"github.com/lalifeier/vvgo-mall/app/sys/service/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dictMixin := schema.Dict{}.Mixin()
	dictMixinHooks0 := dictMixin[0].Hooks()
	dict.Hooks[0] = dictMixinHooks0[0]
	dictMixinFields0 := dictMixin[0].Fields()
	_ = dictMixinFields0
	dictFields := schema.Dict{}.Fields()
	_ = dictFields
	// dictDescCreatedAt is the schema descriptor for created_at field.
	dictDescCreatedAt := dictMixinFields0[0].Descriptor()
	// dict.DefaultCreatedAt holds the default value on creation for the created_at field.
	dict.DefaultCreatedAt = dictDescCreatedAt.Default.(func() time.Time)
	// dictDescCreatedBy is the schema descriptor for created_by field.
	dictDescCreatedBy := dictMixinFields0[1].Descriptor()
	// dict.DefaultCreatedBy holds the default value on creation for the created_by field.
	dict.DefaultCreatedBy = dictDescCreatedBy.Default.(int64)
	// dictDescUpdatedAt is the schema descriptor for updated_at field.
	dictDescUpdatedAt := dictMixinFields0[2].Descriptor()
	// dict.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dict.DefaultUpdatedAt = dictDescUpdatedAt.Default.(func() time.Time)
	// dict.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dict.UpdateDefaultUpdatedAt = dictDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictDescUpdatedBy is the schema descriptor for updated_by field.
	dictDescUpdatedBy := dictMixinFields0[3].Descriptor()
	// dict.DefaultUpdatedBy holds the default value on creation for the updated_by field.
	dict.DefaultUpdatedBy = dictDescUpdatedBy.Default.(int64)
	// dictDescType is the schema descriptor for type field.
	dictDescType := dictFields[1].Descriptor()
	// dict.DefaultType holds the default value on creation for the type field.
	dict.DefaultType = dictDescType.Default.(string)
	// dictDescLabel is the schema descriptor for label field.
	dictDescLabel := dictFields[2].Descriptor()
	// dict.DefaultLabel holds the default value on creation for the label field.
	dict.DefaultLabel = dictDescLabel.Default.(string)
	// dictDescValue is the schema descriptor for value field.
	dictDescValue := dictFields[3].Descriptor()
	// dict.DefaultValue holds the default value on creation for the value field.
	dict.DefaultValue = dictDescValue.Default.(string)
	// dictDescStatus is the schema descriptor for status field.
	dictDescStatus := dictFields[4].Descriptor()
	// dict.DefaultStatus holds the default value on creation for the status field.
	dict.DefaultStatus = dictDescStatus.Default.(int8)
	// dictDescRemark is the schema descriptor for remark field.
	dictDescRemark := dictFields[5].Descriptor()
	// dict.DefaultRemark holds the default value on creation for the remark field.
	dict.DefaultRemark = dictDescRemark.Default.(string)
	// dictDescSort is the schema descriptor for sort field.
	dictDescSort := dictFields[6].Descriptor()
	// dict.DefaultSort holds the default value on creation for the sort field.
	dict.DefaultSort = dictDescSort.Default.(int8)
	// dictDescIsDefault is the schema descriptor for is_default field.
	dictDescIsDefault := dictFields[7].Descriptor()
	// dict.DefaultIsDefault holds the default value on creation for the is_default field.
	dict.DefaultIsDefault = dictDescIsDefault.Default.(int8)
	// dictDescIsDeleted is the schema descriptor for is_deleted field.
	dictDescIsDeleted := dictFields[8].Descriptor()
	// dict.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	dict.DefaultIsDeleted = dictDescIsDeleted.Default.(int8)
}

const (
	Version = "v0.9.2-0.20211030195115-681d03e89680"            // Version of ent codegen.
	Sum     = "h1:3unIS8ZjoiML6TTT1tJjjJjbCHIBNHNtgA7VBIEQZDE=" // Sum of ent codegen.
)
