// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/lalifeier/vvgo-mall/app/sms/interface/internal/biz"
	"github.com/lalifeier/vvgo-mall/app/sms/interface/internal/conf"
	"github.com/lalifeier/vvgo-mall/app/sms/interface/internal/data"
	"github.com/lalifeier/vvgo-mall/app/sms/interface/internal/server"
	"github.com/lalifeier/vvgo-mall/app/sms/interface/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, sms *conf.Sms) (*kratos.App, func(), error) {
	client := data.NewSmsClient(sms)
	redisClient := data.NewRedisClient(confData, logger)
	dataData, cleanup, err := data.NewData(logger, client, redisClient)
	if err != nil {
		return nil, nil, err
	}
	smsRepo := data.NewSmsRepo(dataData, logger)
	smsUsecase := biz.NewSmsUsecase(smsRepo, logger)
	smsService := service.NewSmsService(smsUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, smsService, logger)
	grpcServer := server.NewGRPCServer(confServer, smsService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
