CREATE TABLE `product_comment` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    `sku_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'SKU ID',
    `product_name` varchar(255) NOT NULL DEFAULT '' COMMENT '商品名称',
    `product_attribute` varchar(255) NOT NULL DEFAULT '' COMMENT '商品属性',
    `member_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '评论用户ID',
    `member_name` varchar(255) DEFAULT '' COMMENT '评论用户名',
    `member_icon` varchar(255) DEFAULT '' COMMENT '评论用户头像',
    `member_ip` varchar(255) DEFAULT '' COMMENT '评论用户IP',
    `content` text COMMENT '评论内容',
    `pics` varchar(1000) DEFAULT '' COMMENT '评论图片',
    `comment_score` decimal(10,2) unsigned NOT NULL DEFAULT '0' COMMENT '评分',
    `comment_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '评论数',
    `collect_couont` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '收藏数',
    `read_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '阅读数',
    `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态',
    `is_anonymous` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否匿名',
    `is_show` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否显示',
    `is_delete` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
    `is_top` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否置顶',
    `is_recommend` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否推荐',
    `create_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '评论时间',
    `update_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT AUTO_INCREMENT=666666 CHARSET=utf8mb4 COMMENT='商品评论表';
